#!/bin/bash

# start script for xwax (http://www.xwax.co.uk)
# by rcn @ irc.freenode.net
#
# all configuration is done in the configfile (default: ~/.xwax/config).

# source configuration file
export CONFIGFILE="$HOME/.xwax/config"

if [ -r "$CONFIGFILE" ]; then
    source $CONFIGFILE
else
    echo
    echo "error: $CONFIGFILE doen't exist or is not readable by the user."
    echo
    exit 1
fi

export TW_SWITCH=0
export PLS_SWITCH=0

# evaluate command line parameters
for (( i=1; i<=$#; i++ )) ; do
	case ${!i} in
	'-h'|'--help')
		echo
		echo "start script for xwax (http://www.xwax.co.uk)"
		echo "by rcn @ irc.freenode.net"
		echo
		echo "usage: ${0##*/} [<options>]"
		echo 
		echo "  -h:	print this screen"
		echo "  -pl:	write played tracks to file"
		echo "  -tw:	use the import-twitter script for playlist tweeting"
		echo 
		exit 0
		;;
	'-pl')	export PLS_SWITCH=1
		export PLS_FILE
		if [ ! -d "$PLS_PATH" ]; then mkdir -p "$PLS_PATH"; fi
		;;
	'-tw')	export TW_SWITCH=1
		export TW_CLI
		export TW_LPLYD
		export TW_MSG
		;;
	*)	echo
		echo "unknown option ${!i}. aborting ..."
		echo "use -h to get a list of possible parameters"
		echo
		exit 32
		;;
	esac
done

# delete last_played file at startup (if exists)
if [ -f "$TW_LPLYD" ]; then rm $TW_LPLYD; fi

# create a string of all the crates from the array
CRATESTRING=""; for item in ${CRATE[*]}; do CRATESTRING="$CRATESTRING-l $item "; done

# check for deck protection
if [ $PROT -eq 1 ]; then PROT="-p "; else unset PROT; fi

# run xwax
$XWAX $PROT -r $SRATE -i $IMPORT -s $SCAN $CRATESTRING -m $BTIME -t $TC1 -$RPM1 -a $DECK1 -t $TC2 -$RPM2 -a $DECK2
